import jsPDF from 'jspdf'
import { format } from 'date-fns'

function fmtMin(m) {
  const h = Math.floor(m / 60), min = m % 60
  if (h > 0 && min > 0) return `${h}h ${min}m`
  if (h > 0) return `${h}h`
  return `${min}m`
}

export async function exportStudyReport({ profile, allLogs, t }) {
  const doc  = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const W    = 210
  const M    = 15  // margin
  let y      = 0

  // ── Helpers ─────────────────────────────────────────────────
  const setFont = (size, style = 'normal', color = [20, 20, 20]) => {
    doc.setFontSize(size)
    doc.setFont('helvetica', style)
    doc.setTextColor(...color)
  }

  const drawRect = (x, yy, w, h, r, g, b, fill = true) => {
    doc.setFillColor(r, g, b)
    if (fill) doc.rect(x, yy, w, h, 'F')
    else doc.rect(x, yy, w, h, 'S')
  }

  const txt = (text, x, yy, opts = {}) => {
    const { size = 10, bold = false, color = [30, 30, 30], align = 'left', maxWidth } = opts
    setFont(size, bold ? 'bold' : 'normal', color)
    if (maxWidth) doc.text(String(text), x, yy, { align, maxWidth })
    else          doc.text(String(text), x, yy, { align })
  }

  const line = (x1, yy, x2, r = 220, g = 220, b = 220) => {
    doc.setDrawColor(r, g, b)
    doc.setLineWidth(0.3)
    doc.line(x1, yy, x2, yy)
  }

  const newPage = (needed = 20) => {
    if (y + needed > 275) {
      addFooter()
      doc.addPage()
      y = M
    }
  }

  const addFooter = () => {
    const p = doc.internal.getCurrentPageInfo().pageNumber
    // Bottom blue bar
    doc.setFillColor(14, 165, 233)
    doc.rect(0, 287, W, 10, 'F')
    setFont(8, 'normal', [255, 255, 255])
    doc.text('Generated by HSC PathFinder  •  arnnikislam.vercel.app', W / 2, 293, { align: 'center' })
    doc.text(`Page ${p}`, W - M, 293, { align: 'right' })
  }

  // ── Computed stats ───────────────────────────────────────────
  const totalMins  = allLogs.reduce((s, l) => s + l.minutes, 0)
  const datesSet   = new Set(allLogs.map(l => l.date).filter(Boolean))
  const daysCount  = datesSet.size
  const avgMins    = daysCount > 0 ? Math.round(totalMins / daysCount) : 0
  const goalMins   = (profile?.dailyGoal || 8) * 60
  const goalMetDays = allLogs.reduce((acc, l) => {
    if (!acc.dates) acc.dates = {}
    acc.dates[l.date] = (acc.dates[l.date] || 0) + l.minutes
    return acc
  }, { dates: {} })
  const goalMetCount = Object.values(goalMetDays.dates || {}).filter(m => m >= goalMins).length

  // Group logs by date for daily log table
  const byDate = {}
  allLogs.forEach(l => {
    if (!byDate[l.date]) byDate[l.date] = 0
    byDate[l.date] += l.minutes
  })
  const sortedDates = Object.keys(byDate).sort((a, b) => b.localeCompare(a))

  // ── PAGE 1 ───────────────────────────────────────────────────

  // White background
  doc.setFillColor(255, 255, 255)
  doc.rect(0, 0, W, 297, 'F')

  // ── Top header bar ────────────────────────────────────────────
  doc.setFillColor(14, 165, 233)
  doc.rect(0, 0, W, 38, 'F')

  // Diagonal accent
  doc.setFillColor(249, 115, 22)
  doc.rect(W - 40, 0, 40, 38, 'F')
  // Diagonal mask
  doc.setFillColor(14, 165, 233)
  const triangle = [
    [W - 40, 0], [W - 40, 38], [W - 65, 0]
  ]
  doc.setFillColor(14, 165, 233)
  // Simple diagonal using a polygon
  doc.triangle(W - 65, 0, W - 40, 0, W - 40, 38, 'F')

  setFont(22, 'bold', [255, 255, 255])
  doc.text('HSC PathFinder', M, 16)
  setFont(9, 'normal', [200, 235, 255])
  doc.text('Your Goal, Your Path', M, 24)
  setFont(11, 'bold', [255, 255, 255])
  doc.text('Personal Study Report', M, 33)

  y = 48

  // ── Generated date ────────────────────────────────────────────
  txt(`Generated: ${format(new Date(), 'dd MMMM yyyy  •  hh:mm a')}`, M, y, { size: 8, color: [120, 120, 120] })
  y += 10

  // ── Student info box ──────────────────────────────────────────
  // Box background
  doc.setFillColor(245, 250, 255)
  doc.setDrawColor(14, 165, 233)
  doc.setLineWidth(0.5)
  doc.roundedRect(M, y, W - M * 2, 42, 2, 2, 'FD')

  // Left accent bar
  doc.setFillColor(14, 165, 233)
  doc.rect(M, y, 3, 42, 'F')

  txt('STUDENT INFORMATION', M + 7, y + 7, { size: 8, bold: true, color: [14, 165, 233] })

  // Row 1
  txt('Name',    M + 7,  y + 15, { size: 8, color: [100, 100, 100] })
  txt(':',       M + 25, y + 15, { size: 8, color: [100, 100, 100] })
  txt(profile?.name || '—', M + 29, y + 15, { size: 9, bold: true })

  const grpMap = { science: 'Science', arts: 'Arts', commerce: 'Commerce' }
  txt('Group',   W / 2 + 5, y + 15, { size: 8, color: [100, 100, 100] })
  txt(':',       W / 2 + 20, y + 15, { size: 8, color: [100, 100, 100] })
  txt(grpMap[profile?.group] || '—', W / 2 + 24, y + 15, { size: 9, bold: true })

  // Row 2
  txt('College', M + 7,  y + 23, { size: 8, color: [100, 100, 100] })
  txt(':',       M + 25, y + 23, { size: 8, color: [100, 100, 100] })
  txt(profile?.college || '—', M + 29, y + 23, { size: 9, bold: true })

  txt('Daily Goal', W / 2 + 5, y + 23, { size: 8, color: [100, 100, 100] })
  txt(':',          W / 2 + 22, y + 23, { size: 8, color: [100, 100, 100] })
  txt(`${profile?.dailyGoal || 8}h / day`, W / 2 + 26, y + 23, { size: 9, bold: true, color: [249, 115, 22] })

  // Row 3
  txt('Email',  M + 7,  y + 31, { size: 8, color: [100, 100, 100] })
  txt(':',      M + 25, y + 31, { size: 8, color: [100, 100, 100] })
  txt(profile?.email || '—', M + 29, y + 31, { size: 8 })

  const joined = profile?.joinedAt ? format(new Date(profile.joinedAt), 'dd MMM yyyy') : '—'
  txt('Member Since', W / 2 + 5,  y + 31, { size: 8, color: [100, 100, 100] })
  txt(':',            W / 2 + 26, y + 31, { size: 8, color: [100, 100, 100] })
  txt(joined,         W / 2 + 30, y + 31, { size: 8 })

  y += 52

  // ── Summary stats ─────────────────────────────────────────────
  txt('STUDY SUMMARY', M, y, { size: 9, bold: true, color: [50, 50, 50] })
  y += 2
  line(M, y, W - M)
  y += 5

  const statBoxW = (W - M * 2 - 9) / 4
  const stats = [
    { label: 'Total Study Time', value: fmtMin(totalMins),     accent: [14, 165, 233] },
    { label: 'Days Studied',     value: `${daysCount} days`,   accent: [34, 197, 94]  },
    { label: 'Daily Average',    value: fmtMin(avgMins),        accent: [249, 115, 22] },
    { label: 'Goal Met Days',    value: `${goalMetCount} days`, accent: [168, 85, 247] },
  ]

  stats.forEach((s, i) => {
    const sx = M + i * (statBoxW + 3)
    // Box
    doc.setFillColor(250, 250, 252)
    doc.setDrawColor(230, 230, 240)
    doc.setLineWidth(0.3)
    doc.roundedRect(sx, y, statBoxW, 22, 1.5, 1.5, 'FD')
    // Top accent line
    doc.setFillColor(...s.accent)
    doc.roundedRect(sx, y, statBoxW, 2, 1, 1, 'F')
    // Value
    setFont(11, 'bold', s.accent)
    doc.text(s.value, sx + statBoxW / 2, y + 12, { align: 'center' })
    // Label
    setFont(6.5, 'normal', [120, 120, 120])
    doc.text(s.label, sx + statBoxW / 2, y + 18.5, { align: 'center' })
  })

  y += 30

  // ── Progress bar section ──────────────────────────────────────
  txt('OVERALL PROGRESS', M, y, { size: 9, bold: true, color: [50, 50, 50] })
  y += 2
  line(M, y, W - M)
  y += 5

  // Progress bar background
  const barW = W - M * 2
  doc.setFillColor(235, 235, 240)
  doc.roundedRect(M, y, barW, 6, 3, 3, 'F')

  // Progress fill
  const totalPossibleMins = sortedDates.length * goalMins || 1
  const progressPct = Math.min(1, totalMins / totalPossibleMins)
  doc.setFillColor(14, 165, 233)
  doc.roundedRect(M, y, Math.max(4, barW * progressPct), 6, 3, 3, 'F')

  setFont(7.5, 'bold', [14, 165, 233])
  doc.text(`${Math.round(progressPct * 100)}% of total possible study time`, W - M, y + 4.5, { align: 'right' })
  y += 14

  // ── Daily log table ───────────────────────────────────────────
  newPage(40)
  txt('DAILY STUDY LOG', M, y, { size: 9, bold: true, color: [50, 50, 50] })
  y += 2
  line(M, y, W - M)
  y += 5

  // Table header
  doc.setFillColor(14, 165, 233)
  doc.rect(M, y, W - M * 2, 8, 'F')

  const col = { date: M + 4, dur: M + 80, pct: M + 120, status: M + 150 }
  setFont(8, 'bold', [255, 255, 255])
  doc.text('Date',          col.date,   y + 5.5)
  doc.text('Duration',      col.dur,    y + 5.5)
  doc.text('vs Goal',       col.pct,    y + 5.5)
  doc.text('Status',        col.status, y + 5.5)
  y += 10

  // Table rows
  sortedDates.slice(0, 40).forEach((date, i) => {
    newPage(9)
    const mins    = byDate[date]
    const met     = mins >= goalMins
    const pct     = Math.min(100, Math.round((mins / goalMins) * 100))

    // Alternating row bg
    if (i % 2 === 0) {
      doc.setFillColor(248, 250, 253)
      doc.rect(M, y - 1.5, W - M * 2, 8.5, 'F')
    }

    // Status indicator dot
    doc.setFillColor(...(met ? [34, 197, 94] : [249, 115, 22]))
    doc.circle(col.date - 2, y + 3, 1.2, 'F')

    setFont(8.5, 'normal', [40, 40, 40])
    doc.text(format(new Date(date + 'T00:00:00'), 'EEE, dd MMM yyyy'), col.date, y + 4.5)

    setFont(8.5, met ? 'bold' : 'normal', met ? [34, 197, 94] : [249, 115, 22])
    doc.text(fmtMin(mins), col.dur, y + 4.5)

    setFont(8, 'normal', [100, 100, 100])
    doc.text(`${pct}%`, col.pct, y + 4.5)

    setFont(7.5, 'bold', met ? [34, 197, 94] : [249, 115, 22])
    doc.text(met ? 'Goal Met' : 'Below Goal', col.status, y + 4.5)

    // Bottom separator
    doc.setDrawColor(235, 235, 240)
    doc.setLineWidth(0.2)
    doc.line(M, y + 7, W - M, y + 7)

    y += 8.5
  })

  if (sortedDates.length === 0) {
    doc.setFillColor(248, 250, 253)
    doc.rect(M, y, W - M * 2, 14, 'F')
    setFont(9, 'normal', [150, 150, 150])
    doc.text('No study logs found yet. Start studying and log your hours!', W / 2, y + 9, { align: 'center' })
    y += 18
  }

  y += 6

  // ── Motivational closing ──────────────────────────────────────
  newPage(30)
  doc.setFillColor(240, 247, 255)
  doc.setDrawColor(14, 165, 233)
  doc.setLineWidth(0.4)
  doc.roundedRect(M, y, W - M * 2, 24, 2, 2, 'FD')
  doc.setFillColor(14, 165, 233)
  doc.rect(M, y, 3, 24, 'F')

  setFont(9, 'bold', [14, 165, 233])
  doc.text('Keep Going!', M + 7, y + 8)
  setFont(8, 'normal', [60, 60, 60])
  doc.text('Every hour you study brings you closer to your HSC dream.', M + 7, y + 15, { maxWidth: W - M * 2 - 14 })
  doc.text('You have got this! — HSC PathFinder', M + 7, y + 21)

  // ── Footer on all pages ───────────────────────────────────────
  addFooter()

  // ── Save ─────────────────────────────────────────────────────
  const safeName = (profile?.name || 'Student').replace(/[^a-zA-Z0-9]/g, '_')
  doc.save(`HSC-PathFinder-Report-${safeName}-${format(new Date(), 'yyyy-MM-dd')}.pdf`)
}
